steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'export']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'run', '-p', '8081:8081',
      '--env', 'PORT=8081',
      'node', '.next/standalone/server.js'
    ]
